<!--
	Lesson 9A.3 — a JSON inspector that renders the raw shape of `data`.
	Hover over `data.demo` in your editor — the tooltip shows the generated
	type from ./$types, not any hand-written interface.
-->
<script lang="ts">
	import type { PageProps } from './$types';

	let { data }: PageProps = $props();

	const serialised: string = JSON.stringify(data, null, 2);
</script>

<svelte:head>
	<title>Lesson 9A.3 · Auto types · Ultimate Frontend</title>
	<meta
		name="description"
		content="Lesson 9A.3 mini-build — a JSON inspector that shows the auto-generated PageProps type in action."
	/>
</svelte:head>

<section class="page stack">
	<nav class="crumbs" aria-label="Breadcrumb">
		<a href="/modules/09a-load">← Module 9A</a>
	</nav>

	<header>
		<p class="eyebrow">Lesson 9A.3 · Mini-build</p>
		<h1>The generated data shape</h1>
		<p class="lede">
			The block below is the raw value of <code>data</code>. Its type was generated by SvelteKit
			from the return of the colocated <code>+page.ts</code> — you never wrote it by hand.
		</p>
	</header>

	<pre class="inspector" aria-label="data prop">{serialised}</pre>

	<aside class="hint">
		<p>
			Open this file in your editor and hover over <code>data.demo.name</code>. Your editor will
			show you that it is a <code>string</code>. Change the return of <code>+page.ts</code> and
			the type updates automatically on the next save.
		</p>
	</aside>
</section>

<style>
	section {
		--color-brand: oklch(70% 0.18 150);
	}

	.crumbs a {
		font-size: var(--text-sm);
		color: var(--color-text-muted);
		text-decoration: none;
	}

	.eyebrow {
		font-size: var(--text-sm);
		color: var(--color-brand);
		text-transform: uppercase;
		letter-spacing: 0.08em;
	}

	.lede {
		font-size: var(--text-lg);
		color: var(--color-text-muted);
		max-inline-size: 60ch;
	}

	.inspector {
		padding: var(--space-lg);
		background: var(--color-surface-2);
		border: 1px solid var(--color-border);
		border-inline-start: 4px solid var(--color-brand);
		border-radius: var(--radius-lg);
		font-family: ui-monospace, 'SF Mono', Menlo, Consolas, monospace;
		font-size: var(--text-sm);
		color: var(--color-brand);
		overflow-x: auto;
		white-space: pre;
	}

	.hint {
		padding: var(--space-md);
		border-inline-start: 3px solid var(--color-brand);
		background: var(--color-surface-2);
		border-radius: var(--radius-md);
		font-size: var(--text-sm);
		color: var(--color-text-muted);
	}
</style>
