<script lang="ts">
	interface Migration {
		id: string;
		name: string;
		sql: string;
		status: 'applied' | 'pending';
		appliedAt: string;
	}

	const migrations: Migration[] = [
		{
			id: '0000',
			name: 'create_users_table',
			sql: `CREATE TABLE \`users\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  \`name\` text NOT NULL,
  \`email\` text NOT NULL,
  \`created_at\` text NOT NULL
);
CREATE UNIQUE INDEX \`users_email_unique\` ON \`users\` (\`email\`);`,
			status: 'applied',
			appliedAt: '2026-05-10T09:00:00Z'
		},
		{
			id: '0001',
			name: 'create_notes_table',
			sql: `CREATE TABLE \`notes\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  \`title\` text NOT NULL,
  \`content\` text NOT NULL DEFAULT '',
  \`user_id\` integer NOT NULL REFERENCES \`users\`(\`id\`),
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL
);`,
			status: 'applied',
			appliedAt: '2026-05-11T14:30:00Z'
		},
		{
			id: '0002',
			name: 'create_tags_and_junction',
			sql: `CREATE TABLE \`tags\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  \`name\` text NOT NULL
);
CREATE UNIQUE INDEX \`tags_name_unique\` ON \`tags\` (\`name\`);

CREATE TABLE \`notes_tags\` (
  \`note_id\` integer NOT NULL REFERENCES \`notes\`(\`id\`),
  \`tag_id\` integer NOT NULL REFERENCES \`tags\`(\`id\`),
  PRIMARY KEY (\`note_id\`, \`tag_id\`)
);`,
			status: 'applied',
			appliedAt: '2026-05-12T11:15:00Z'
		}
	];

	function formatDate(iso: string): string {
		return new Date(iso).toLocaleDateString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric',
			hour: '2-digit',
			minute: '2-digit'
		});
	}
</script>

<svelte:head>
	<title>Lesson 16.4 · Migrations · Ultimate Frontend</title>
	<meta
		name="description"
		content="Visualizing database migrations as a timeline: how schema changes are tracked and applied with drizzle-kit."
	/>
</svelte:head>

<section class="page stack">
	<nav class="crumbs" aria-label="Breadcrumb">
		<a href="/modules/16-database">← Module 16</a>
	</nav>

	<header>
		<p class="eyebrow">Lesson 16.4 · Mini-build</p>
		<h1>Migration timeline</h1>
		<p class="lede">
			Each card represents a migration generated by <code>drizzle-kit generate</code>.
			Migrations are applied in order and tracked by the database.
		</p>
	</header>

	<ol class="timeline" aria-label="Migration history">
		{#each migrations as migration (migration.id)}
			<li class="timeline__item">
				<div class="timeline__marker"></div>
				<article class="migration-card">
					<header class="migration-card__header">
						<span class="migration-card__id">{migration.id}</span>
						<h2 class="migration-card__name">{migration.name}</h2>
						<span class="migration-card__status migration-card__status--{migration.status}">
							{migration.status}
						</span>
					</header>
					<pre class="migration-card__sql"><code>{migration.sql}</code></pre>
					<footer class="migration-card__footer">
						<time datetime={migration.appliedAt}>
							Applied: {formatDate(migration.appliedAt)}
						</time>
					</footer>
				</article>
			</li>
		{/each}
	</ol>

	<article class="explanation">
		<h2>The workflow</h2>
		<ol class="workflow-steps">
			<li>Edit <code>src/lib/server/db/schema.ts</code></li>
			<li>Run <code>pnpm drizzle-kit generate</code></li>
			<li>Review the generated SQL file</li>
			<li>Run <code>pnpm drizzle-kit migrate</code></li>
			<li>Commit both schema and migration to git</li>
		</ol>
	</article>
</section>

<style>
	section.page {
		--color-brand: oklch(68% 0.17 55);
	}

	.crumbs a {
		color: var(--color-text-muted);
		text-decoration: none;
		font-size: var(--text-sm);
		min-block-size: 44px;
		display: inline-flex;
		align-items: center;
	}

	.eyebrow {
		font-size: var(--text-sm);
		color: var(--color-brand);
		text-transform: uppercase;
		letter-spacing: 0.08em;
	}

	.lede {
		color: var(--color-text-muted);
		font-size: var(--text-lg);
		max-inline-size: var(--prose-max);
	}

	.timeline {
		list-style: none;
		padding: 0;
		margin: 0;
		position: relative;
		padding-inline-start: var(--space-lg);
	}

	.timeline::before {
		content: '';
		position: absolute;
		inset-inline-start: 8px;
		inset-block-start: 0;
		inset-block-end: 0;
		inline-size: 2px;
		background: var(--color-border);
	}

	.timeline__item {
		position: relative;
		padding-block-end: var(--space-lg);
	}

	.timeline__marker {
		position: absolute;
		inset-inline-start: calc(-1 * var(--space-lg) + 2px);
		inset-block-start: 0.5em;
		inline-size: 14px;
		block-size: 14px;
		border-radius: var(--radius-full);
		background: var(--color-brand);
		border: 2px solid var(--color-surface);
	}

	.migration-card {
		padding: var(--space-md);
		background: var(--color-surface-2);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-lg);
	}

	.migration-card__header {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: var(--space-sm);
		margin-block-end: var(--space-sm);
	}

	.migration-card__id {
		font-family: ui-monospace, monospace;
		font-size: var(--text-xs);
		color: var(--color-text-muted);
		background: var(--color-surface);
		padding: 0.15em 0.5em;
		border-radius: var(--radius-sm);
	}

	.migration-card__name {
		font-size: var(--text-base);
		font-family: ui-monospace, monospace;
		margin: 0;
		flex: 1;
	}

	.migration-card__status {
		font-size: var(--text-xs);
		padding: 0.15em 0.6em;
		border-radius: var(--radius-full);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		font-weight: 600;
	}

	.migration-card__status--applied {
		background: var(--color-success);
		color: oklch(15% 0.02 145);
	}

	.migration-card__status--pending {
		background: var(--color-warning);
		color: oklch(20% 0.02 85);
	}

	.migration-card__sql {
		margin: 0;
		padding: var(--space-sm);
		background: var(--color-surface);
		border-radius: var(--radius-md);
		overflow-x: auto;
		font-size: var(--text-sm);
		line-height: 1.5;
	}

	.migration-card__footer {
		margin-block-start: var(--space-sm);
	}

	.migration-card__footer time {
		font-size: var(--text-sm);
		color: var(--color-text-muted);
	}

	.explanation {
		padding: var(--space-lg);
		background: var(--color-surface-2);
		border: 1px solid var(--color-border);
		border-inline-start: 4px solid var(--color-brand);
		border-radius: var(--radius-lg);
	}

	.explanation h2 {
		font-size: var(--text-lg);
		margin: 0 0 var(--space-sm);
	}

	.workflow-steps {
		padding-inline-start: var(--space-md);
	}

	.workflow-steps li {
		padding-block: var(--space-xs);
	}
</style>
