<script lang="ts">
	interface MessageDef {
		key: string;
		pattern: string;
		params: string[];
	}

	let messages: MessageDef[] = $state([
		{ key: 'greeting', pattern: 'Welcome, {name}!', params: ['name'] },
		{ key: 'item_count', pattern: '{count, plural, =0 {No items} one {# item} other {# items}}', params: ['count'] },
		{ key: 'page_title', pattern: 'Dashboard', params: [] }
	]);

	let activeLocale: string = $state('en');
	const locales: string[] = ['en', 'pt-BR', 'ar'];

	const localeTranslations: Record<string, Record<string, string>> = {
		'en': { greeting: 'Welcome, {name}!', item_count: '{count, plural, =0 {No items} one {# item} other {# items}}', page_title: 'Dashboard' },
		'pt-BR': { greeting: 'Bem-vindo, {name}!', item_count: '{count, plural, =0 {Nenhum item} one {# item} other {# itens}}', page_title: 'Painel' },
		'ar': { greeting: '!{name} ,مرحبا', item_count: '{count, plural, =0 {لا عناصر} one {عنصر #} two {عنصران} few {# عناصر} many {# عنصرا} other {# عنصر}}', page_title: 'لوحة القيادة' }
	};

	function compileToFunction(key: string, pattern: string): string {
		const params = [...pattern.matchAll(/\{(\w+?)(?:,|\})/g)].map((m) => m[1]);
		const uniqueParams = [...new Set(params)];

		if (uniqueParams.length === 0) {
			return `export function ${key}(): string {\n  return "${pattern}";\n}`;
		}

		const paramTypes: string = uniqueParams
			.map((p) => {
				if (pattern.includes(`${p}, plural`) || pattern.includes(`${p},plural`)) {
					return `${p}: number`;
				}
				return `${p}: string`;
			})
			.join('; ');

		return `export function ${key}(params: { ${paramTypes} }): string {\n  // Compiled from ICU pattern\n  const { ${uniqueParams.join(', ')} } = params;\n  return \`${pattern.replace(/\{(\w+)\}/g, '${$1}')}\`;\n}`;
	}

	let compiledOutput: string = $derived(
		`// Generated by Paraglide — ${activeLocale}.ts\n// Do not edit manually.\n\n` +
		messages
			.map((m) => compileToFunction(m.key, localeTranslations[activeLocale]?.[m.key] ?? m.pattern))
			.join('\n\n')
	);

	let newKey: string = $state('');
	let newPattern: string = $state('');

	function addMessage(): void {
		if (!newKey.trim() || !newPattern.trim()) return;
		const params = [...newPattern.matchAll(/\{(\w+?)(?:,|\})/g)].map((m) => m[1]);
		messages = [...messages, { key: newKey.trim(), pattern: newPattern.trim(), params: [...new Set(params)] }];
		for (const locale of locales) {
			if (!localeTranslations[locale]) localeTranslations[locale] = {};
			localeTranslations[locale][newKey.trim()] = newPattern.trim();
		}
		newKey = '';
		newPattern = '';
	}
</script>

<svelte:head>
	<title>19.3 — Paraglide.js with SvelteKit · Internationalization</title>
</svelte:head>

<section class="page stack">
	<header>
		<p class="eyebrow">Lesson 19.3 · Mini-build</p>
		<h1>Paraglide Compilation Simulator</h1>
		<p class="lede">
			See how Paraglide compiles ICU message patterns into type-safe
			TypeScript functions for each locale.
		</p>
	</header>

	<nav class="locale-tabs" aria-label="Locale selector">
		{#each locales as locale}
			<button
				class="locale-tab"
				class:locale-tab--active={activeLocale === locale}
				onclick={() => activeLocale = locale}
			>
				{locale}
			</button>
		{/each}
	</nav>

	<div class="panels">
		<section class="panel" aria-labelledby="messages-heading">
			<h2 id="messages-heading" class="panel__title">Message Definitions ({activeLocale})</h2>
			<ul class="message-list">
				{#each messages as msg (msg.key)}
					<li class="message-item">
						<code class="message-item__key">{msg.key}</code>
						<span class="message-item__pattern">{localeTranslations[activeLocale]?.[msg.key] ?? msg.pattern}</span>
						{#if msg.params.length > 0}
							<span class="message-item__params">
								params: {msg.params.join(', ')}
							</span>
						{/if}
					</li>
				{/each}
			</ul>

			<form class="add-form" onsubmit={(e) => { e.preventDefault(); addMessage(); }}>
				<input
					type="text"
					class="add-form__input"
					bind:value={newKey}
					placeholder="Message key"
				/>
				<input
					type="text"
					class="add-form__input"
					bind:value={newPattern}
					placeholder="ICU pattern"
				/>
				<button type="submit" class="btn">Add</button>
			</form>
		</section>

		<section class="panel panel--output" aria-labelledby="compiled-heading">
			<h2 id="compiled-heading" class="panel__title">Compiled Output ({activeLocale}.ts)</h2>
			<pre class="compiled-code"><code>{compiledOutput}</code></pre>
		</section>
	</div>
</section>

<style>
	.eyebrow {
		font-size: var(--text-sm);
		color: var(--color-brand);
		letter-spacing: 0.08em;
		text-transform: uppercase;
		font-weight: 700;
	}

	.lede {
		font-size: var(--text-lg);
		color: var(--color-text-muted);
		max-inline-size: 50ch;
	}

	.locale-tabs {
		display: flex;
		gap: var(--space-xs);
	}

	.locale-tab {
		padding: var(--space-xs) var(--space-md);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		font-size: var(--text-sm);
		font-weight: 600;
		min-block-size: 44px;
		transition: all var(--dur-fast) var(--ease-out);
	}

	.locale-tab:hover {
		border-color: var(--color-brand);
	}

	.locale-tab--active {
		background: var(--color-brand);
		color: oklch(100% 0 0);
		border-color: var(--color-brand);
	}

	.panels {
		display: grid;
		gap: var(--space-md);
	}

	@media (min-width: 768px) {
		.panels {
			grid-template-columns: 1fr 1fr;
		}
	}

	.panel {
		padding: var(--space-md);
		background: var(--color-surface-2);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-lg);
	}

	.panel--output {
		border-color: var(--color-brand);
	}

	.panel__title {
		font-size: var(--text-sm);
		font-weight: 700;
		color: var(--color-brand);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		margin-block-end: var(--space-md);
	}

	.message-list {
		list-style: none;
		padding: 0;
		margin: 0;
		display: grid;
		gap: var(--space-sm);
		margin-block-end: var(--space-md);
	}

	.message-item {
		padding: var(--space-sm);
		background: var(--color-surface);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		display: grid;
		gap: 0.2rem;
	}

	.message-item__key {
		font-size: var(--text-xs);
		color: var(--color-brand);
		font-weight: 700;
	}

	.message-item__pattern {
		font-size: var(--text-sm);
		word-break: break-word;
	}

	.message-item__params {
		font-size: var(--text-xs);
		color: var(--color-text-muted);
	}

	.add-form {
		display: flex;
		gap: var(--space-xs);
		flex-wrap: wrap;
	}

	.add-form__input {
		flex: 1;
		min-inline-size: 8rem;
		padding: var(--space-xs) var(--space-sm);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-sm);
		background: var(--color-surface);
		font-size: var(--text-sm);
		min-block-size: 44px;
	}

	.btn {
		padding: var(--space-xs) var(--space-md);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		font-size: var(--text-sm);
		font-weight: 600;
		min-block-size: 44px;
		transition: border-color var(--dur-fast) var(--ease-out);
	}

	.btn:hover {
		border-color: var(--color-brand);
	}

	.compiled-code {
		background: var(--color-surface);
		padding: var(--space-md);
		border-radius: var(--radius-md);
		overflow-x: auto;
		font-size: var(--text-xs);
		line-height: 1.6;
		white-space: pre;
	}
</style>
